//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatcherDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuel_delivery_event
    {
        public int pkey { get; set; }
        public int current_stop { get; set; }
        public int next_stop { get; set; }
        public int current_fuel_level { get; set; }
        public System.DateTime stop_datetime { get; set; }
    }
}
